services:
  qbittorrent:
    hostname: qbittorrent.internal
    container_name: qbittorrent
    image: ghcr.io/hotio/qbittorrent
    networks:
      - proxy
      - autotorrents_default
      #ports:
      #- 8080:8080
    restart: unless-stopped
    volumes:
      - ./qbitconfig:/config
      - ${MEDIAFILEPATH}/torrentdownloads:/media/torrentdownloads
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=002
      - TZ=${TZ}
      - WEBUI_PORTS=8080/tcp,8080/udp
      - LIBTORRENT=v1
      - VPN_ENABLED=true
      - VPN_CONF=wg0
      - VPN_PROVIDER=proton
      - VPN_LAN_NETWORK=${VPN_LAN_NETWORK}
      - VPN_LAN_LEAK_ENABLED=false
      - VPN_AUTO_PORT_FORWARD=true
      - VPN_AUTO_PORT_FORWARD_TO_PORTS=
      - VPN_FIREWALL_TYPE=auto
      - VPN_HEALTHCHECK_ENABLED=true
      - PRIVOXY_ENABLED=false
      - UNBOUND_ENABLED=false
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=1
    devices:
      - /dev/net/tun:/dev/net/tun
    labels:
      - traefik.enable=true
      - traefik.http.routers.qbit.rule=Host(`qbit.${SUBDOMAIN}`)
      - traefik.http.routers.qbit.entrypoints=websecure
      - traefik.http.routers.qbit.tls.certresolver=cloudflare
      - traefik.http.services.qbit.loadbalancer.server.port=8080
      # (Optional) gzip compression for UI
      - traefik.http.middlewares.qbit-compress.compress=true
      - traefik.http.routers.qbit.middlewares=authentik@docker,qbit-compress
networks:
  autotorrents_default:
    external: true
  proxy:
    external: true
