services:
  beszel:
    image: henrygd/beszel:latest
    container_name: beszel
    #user: ${PUID}:${PGID}
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    #ports:
    #- 8090:8090
    volumes:
      - ./beszel_data:/beszel_data
      - ./beszel_socket:/beszel_socket
    networks:
      - proxy
      - beszel_default
    labels:
      - traefik.enable=true
      - traefik.http.routers.beszel.rule=Host(`beszel.${SUBDOMAIN}`)
      - traefik.http.routers.beszel.entrypoints=websecure
      - traefik.http.routers.beszel.tls.certresolver=cloudflare
      - traefik.http.services.beszel.loadbalancer.server.port=8090
  beszel-agent:
    #user: ${PUID}:${PGID}
    image: henrygd/beszel-agent:latest
    container_name: beszel-agent
    restart: unless-stopped
    #network_mode: host
    volumes:
      - ./beszel_agent_data:/var/lib/beszel-agent
      - ./beszel_socket:/beszel_socket
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      LISTEN: /beszel_socket/beszel.sock
      HUB_URL: https://beszel.${SUBDOMAIN}
      TOKEN: ${TOKEN}
      KEY: ${KEY}
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    networks:
      - beszel_default
networks:
  beszel_default:
    name: beszel_default
    driver: bridge
  proxy:
    external: true
